#pragma once

#ifndef PICOMQTT_MAX_TOPIC_SIZE
#define PICOMQTT_MAX_TOPIC_SIZE 128
#endif

#ifndef PICOMQTT_MAX_MESSAGE_SIZE
#define PICOMQTT_MAX_MESSAGE_SIZE 1024
#endif

#ifndef PICOMQTT_MAX_CLIENT_ID_SIZE
#define PICOMQTT_MAX_CLIENT_ID_SIZE 23
#endif

#ifndef PICOMQTT_MAX_USERPASS_SIZE
#define PICOMQTT_MAX_USERPASS_SIZE 16
#endif

#ifndef PICOMQTT_OUTGOING_BUFFER_SIZE
#define PICOMQTT_OUTGOING_BUFFER_SIZE 128
#endif

// #define PICOMQTT_DEBUG

// #define PICOMQTT_DEBUG_TRACE_FUNCTIONS
