[env]
framework = arduino
lib_ldf_mode = deep
lib_deps = symlink://../../
monitor_speed = 115200
upload_speed = 921600
build_flags =
	-DWIFI_SSID=\"${sysenv.WIFI_SSID}\"
	-DWIFI_PASSWORD=\"${sysenv.WIFI_PASSWORD}\"

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2

[env:esp32dev]
platform = espressif32
board = esp32dev
