---
name: CI

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: arduino/arduino-lint-action@v1
        with:
          compliance: strict
          library-manager: update
          project-type: library

  build:
    strategy:
      matrix:
        include:
          - board: d1_mini
            platform_override:
          - board: esp32dev
            platform_override: espressif32@6.9.0
          - board: esp32dev
            platform_override: https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
          - board: giga_r1_m7
            platform_override: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install jq
        run: sudo apt-get install -yq jq
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - name: Build examples
        run: PLATFORM_OVERRIDE=${{ matrix.platform_override }} ./build_examples.sh ${{ matrix.board }}
