name: Publish to PlatformIO Registry

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
      - name: Install PlatformIO Core
        run: pip install -U platformio
      - name: Publish library
        run: |
          pio package publish --owner '${{ secrets.PLATFORMIO_OWNER }}' --token '${{ secrets.PLATFORMIO_AUTH_TOKEN }}'
